### ISSUE TITLE
Breakout polypolish read mapping to its own rule.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#123]
One more thought: if we wanted, we could separate the read mapping step for polypolish from polypolish itself. The read mapping step can be highly parallelized, whereas I think polypolish only runs with a single thread. This doesn't have to be done now, but it could be a nice optimization.

_Originally posted by @jmtsuji in https://github.com/rotary-genomics/rotary/issues/122#issuecomment-1940404380_

**Comment by jmtsuji** [comment]
Addressed in #125
