### ISSUE TITLE
Add flag to keep final QC read files

### ISSUE THREAD

**Issue by jmtsuji** [jmtsuji/rotary#129]
Similar to #119 , I often find it helpful to keep the final QC files for short/long reads so that I can check the quality of the assembly, redo read mapping, and so on. Like #119 , I am interested in adding a flag to the config file so that the final long/short read QC files are not temp() -- what do you think @LeeBergstrand ?

**Comment by LeeBergstrand** [comment]
@jmtsuji That could work. I would be open to that. We might want to mention in the docs that they can run `--no-temp` to keep all the intermediary files. I think that a config flag for this is OK.

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/rotary-genomics/rotary/pull/130
