### ISSUE TITLE
DB error for CheckM2

### ISSUE THREAD

**Issue by jmtsuji** [jmtsuji/rotary#164]
# System info
Running rotary commit 580b0b4 on Ubuntu 22.04 LTS

# Problem description
In `rule run_checkm2`, `checkm2 predict` currently doesn't specify the DB dir location:
```bash
mkdir -p {output.outdir}
checkm2 predict --threads {threads} --input {input.genome} --output-directory {output.outdir} > {log} 2>&1
mv {output.outdir}/quality_report.tsv {output.quality_report}
```

This is not a problem the first time that rotary is run end-to-end, because I think `checkm2 database --download` sets the DB dir location internally within `checkm2`. However, after using the same rotary DB dir for a while, in my experience, eventually a new install of `checkm2` is created by snakemake (e.g., due to updates to the rotary code). This updated `checkm2` install doesn't know where the DB is, causing a missing DB error.

# Proposed solution
`checkm2 predict` comes with a `--database_path` flag:
```
--database_path DATABASE_PATH
                        Provide a location for the CheckM2 database for a given predict run [default: use either internal path set via <checkm2 database> or CHECKM2DB environmental variable]
```

I propose that we add this flag to the `rule run_checkm2` shell command.

# Possible caveats
If a major version change of CheckM2 ever occurs and a new CheckM2 DB is released, then the user still might run into a DB error with this strategy. We would need to link the CheckM2 DB to the associated CheckM2 version, like we've done with the GTDB, to address this.

**Comment by jmtsuji** [comment]
Addressed in #165 , aside from the caveat above. We can potentially address the caveat above if/when CheckM2 has a DB update -- @LeeBergstrand sounds good?

**Comment by LeeBergstrand** [comment]
> If a major version change of CheckM2 ever occurs and a new CheckM2 DB is released, then the user still might run into a DB error with this strategy. We would need to link the CheckM2 DB to the associated CheckM2 version, like we've done with the GTDB, to address this.

@jmtsuji I assume that the user can delete the checkm2 database checkpoint to redownload the database from scratch as a stop gap?

**Comment by LeeBergstrand** [comment]
> Addressed in #165 , aside from the caveat above. We can potentially address the caveat above if/when CheckM2 has a DB update -- @LeeBergstrand sounds good?

Sounds good. Let's create a separate issue for this.

**Comment by jmtsuji** [comment]
> > Addressed in #165 , aside from the caveat above. We can potentially address the caveat above if/when CheckM2 has a DB update -- @LeeBergstrand sounds good?
> 
> Sounds good. Let's create a separate issue for this.

Sounds good.

**Comment by jmtsuji** [comment]
> > If a major version change of CheckM2 ever occurs and a new CheckM2 DB is released, then the user still might run into a DB error with this strategy. We would need to link the CheckM2 DB to the associated CheckM2 version, like we've done with the GTDB, to address this.
> 
> @jmtsuji I assume that the user can delete the checkm2 database checkpoint to redownload the database from scratch as a stop gap?

Yes, this will work as a stopgap. So far, I don't think the checkm2 database has updated since the tool was released... it might not be updated frequently.

**Comment by LeeBergstrand** [comment]
Added issue: https://github.com/rotary-genomics/rotary/issues/166
