### ISSUE TITLE
Delete Unused Branches

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#167]
Delete Unused Branches

![image](https://github.com/rotary-genomics/rotary/assets/5819462/190306e2-8b90-445f-8768-3995b264e827)

@jmtsuji Can any of these branches be deleted?

**Comment by LeeBergstrand** [comment]
@jmtsuji We could delete the update_patch and the rotate and stitch module branches correct?

**Comment by jmtsuji** [comment]
Yes, let's delete these 3 stale branches -- thanks for flagging them.

**Comment by jmtsuji** [comment]
Will delete now.

**Comment by LeeBergstrand** [comment]
Great!
