### ISSUE TITLE
Snakemake can't find sequencing files if --directory output_dir is used.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#27]
### Problem Description

When running the default command as recommended in the readme. I get an error saying the long-read file cannot be found.

```bash
snakemake --snakefile rotary/rules/rotary.smk \
  --configfile myconfig.yaml \
  --directory output_dir \
  --conda-prefix conda_envs \
  --jobs 20 \
  --use-conda \
  --conda-frontend mamba \
  --rerun-incomplete \
  --reason \
  --printshellcmds 2>&1 | \
  tee rotary.log
```

### Problem Solution (Bodge)

Replaced ```  --directory output_dir  ``` with ```  --directory ./ ```. Does it want me to put the input files in the output directory?

**Comment by jmtsuji** [comment]
@LeeBergstrand Sorry, this is poorly documented, but the absolute paths to the input files are needed in the config file (I think this might be why you are running into trouble). Does that help?

**Comment by LeeBergstrand** [comment]
@jmtsuji Thanks
