### ISSUE TITLE
PFAM website is being shutdown. Start HMM can no longer be downloaded.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#29]
### Problem Description
I get the following error in ```hmm_download.log```:

```
--2023-09-29 16:15:44--  https://pfam.xfam.org/family/PF00308/hmm
Resolving pfam.xfam.org (pfam.xfam.org)... 193.62.193.83
Connecting to pfam.xfam.org (pfam.xfam.org)|193.62.193.83|:443... connected.
ERROR: no certificate subject alternative name matches
        requested host name ‘pfam.xfam.org’.
To connect to pfam.xfam.org insecurely, use `--no-check-certificate'.
```

The HTTPS certificate for Xfam had expired or something close to that, so the download failed.

### Problem Solution

I added the ```--no-check-certificate``` to the download HMM rule.

```
rule download_hmm:
    output:
        hmm=os.path.join(config.get("db_dir"), "hmm", config.get("start_hmm_pfam_id") + ".hmm")
    log:
        "logs/download/hmm_download.log"
    benchmark:
        "benchmarks/download/hmm_download.txt"
    params:
        db_dir=os.path.join(config.get("db_dir"), "hmm"),
        url="https://pfam.xfam.org/family/" + config.get("start_hmm_pfam_id") + "/hmm"
    shell:
        """
        mkdir -p {params.db_dir}
        wget -O {output.hmm} --no-check-certificate {params.url} 2> {log}
        """
```

Note that this allows the HMM to be downloaded but has security implications.

**Comment by LeeBergstrand** [comment]
Okay, this downloads an HTML file rather than the HMM itself.

**Comment by LeeBergstrand** [comment]
Okay, so the PFAM website is being shutdown. So we will have to get the HMM from a different source.

![Screen Shot 2023-09-29 at 1 39 51 PM](https://github.com/jmtsuji/rotary/assets/5819462/1a105d0d-aacc-46b3-9a16-6bd12c5e28fc)

**Comment by LeeBergstrand** [comment]
Okay, the URL http://pfam-legacy.xfam.org/family/PF08299/hmm works, but the HMM will not be updated as all updates will be done on InterPro. On Interpro, you cannot download individual HMMs, and the batch download of all PFAMs returns one big HMM file for all PFAMs.

**Comment by LeeBergstrand** [comment]
@jmtsuji So, do we eventually start batch downloading all of PFAM and running part of the big HMM? I wonder if you can tell HMMER to run just one ID out of an HMM or extract PF08299 from the bigger HMM. Thoughts?

**Comment by LeeBergstrand** [comment]
Temporary fixed added in https://github.com/jmtsuji/rotary/commit/9dfd461b89aff91aac0f2dd4dd58392dc8464871

**Comment by jmtsuji** [comment]
@LeeBergstrand Thanks for looking into this issue. Too bad that the new hosting setup for Pfam HMMs is not ideal for single-HMM download....

One option is to change to the TIGRFAM rpoB HMM, which is hosted at NCBI: https://www.ncbi.nlm.nih.gov/genome/annotation_prok/evidence/TIGR02013/

It's possible to download the HMM as a single file: https://ftp.ncbi.nlm.nih.gov/hmm/current/hmm_PGAP.HMM/TIGR02013.1.HMM

Thoughts?

**Comment by jmtsuji** [comment]
> Temporary fixed added in [9dfd461](https://github.com/jmtsuji/rotary/commit/9dfd461b89aff91aac0f2dd4dd58392dc8464871)

Thanks for adding this temporary fix!

**Comment by LeeBergstrand** [comment]
> @LeeBergstrand Thanks for looking into this issue. Too bad that the new hosting setup for Pfam HMMs is not ideal for single-HMM download....
> 
> One option is to change to the TIGRFAM rpoB HMM, which is hosted at NCBI: https://www.ncbi.nlm.nih.gov/genome/annotation_prok/evidence/TIGR02013/
> 
> It's possible to download the HMM as a single file: https://ftp.ncbi.nlm.nih.gov/hmm/current/hmm_PGAP.HMM/TIGR02013.1.HMM
> 
> Thoughts?

From TIGRFAMS NCBI site:

```
The TIGRFAMs database was transferred in April 2018 to the National Center for Biotechnology Information (NCBI), which
now holds the creative commons license to this data and is responsible for maintaining and distributing this intellectual 
property. The database is used in NCBI's Prokaryotic Genome Annotation Pipeline for GenBank and RefSeq sequence 
annotation, and curators continue to revise existing models. 
```

Okay, so from this description, the models are being updated. That would be my main concern. Also, TIGERFAM are whole gene HMMs, so they should be more specific.

@jmtsuji Let's go with the TIGRFAM rpoB HMM.

**Comment by jmtsuji** [comment]
Sounds good!

**Comment by LeeBergstrand** [comment]
@jmtsuji Code for this has been committed here: https://github.com/jmtsuji/rotary/tree/new_hmm_download

I had trouble running it because I think the development branch of Rotary doesn't call these rules yet. Even when I ran snakemake's ```--forceall``` flag. Does this branch have to be integrated into your repair ends branch?

**Comment by jmtsuji** [comment]
I'm not sure why you had trouble running this rule -- so long as you have circular contigs, it should in theory run (independently of end repair). However, snakemake won't know that it needs to run this code until it reaches a checkpoint partway through the pipeline and verifies that you actually have circular contigs. This is not ideal (it would be better if we had a rapid and guaranteed way of testing this rule), so I think this could be another reason to make a dedicated download rule/function as described in #45 

Anyway, I tested the new rule in the end repair branch, and it works! Thus, I will close this issue.

**Comment by LeeBergstrand** [comment]
@jmtsuji Sounds good!
