### ISSUE TITLE
Default Egg Nog Mapper Mode

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#30]
@jmtsuji So, in the default ```config.yml```, the default eggnog mapper sense mode is set to ```ultra-sensitive```. Does this take much more time to run versus the other modes? So should the default be ```ultra-sensitive``` or something more in the middle, like the ```sensitive``` setting?

```yaml
# EggNOG annotation sensitivity mode (using DIAMOND)
#    Options: fast, mid-sensitive, sensitive, more-sensitive, very-sensitive, ultra-sensitive
eggnog_sensmode: "ultra-sensitive"
```

**Comment by jmtsuji** [comment]
Sure, changing to `sensitive` sounds fine to me. We were only running one genome at a time when I first built rotary and wanted maximum accuracy, but this is not reflective of the needs of all users. Are you OK to make this change (e.g., to develop)?

**Comment by LeeBergstrand** [comment]
> Sure, changing to `sensitive` sounds fine to me. We were only running one genome at a time when I first built rotary and wanted maximum accuracy, but this is not reflective of the needs of all users. Are you OK to make this change (e.g., to develop)?

Will do!

**Comment by jmtsuji** [comment]
Thanks!
