### ISSUE TITLE
GTDBtk fails to due to prodigal's Non-Zero exit code.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#31]
### Problem Description

The rule ```run_gtdbtk``` fails due to the following error.

```
[2023-09-29 17:11:21] INFO: Identifying markers in 1 genomes with 4 threads.
[2023-09-29 17:11:21] TASK: Running Prodigal V2.6.3 to identify genes.
[2023-09-29 17:11:42] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: ProdigalException
  MESSAGE: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/lbergstrand/rnd/hybrid_assembly_pipeline/scratch_space/conda_envs/e64245cbfbbe74933ee636d603a82d12_/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 211, in run
    raise ProdigalException('Prodigal returned a non-zero exit code.')
gtdbtk.exceptions.ProdigalException: Prodigal returned a non-zero exit code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lbergstrand/rnd/hybrid_assembly_pipeline/scratch_space/conda_envs/e64245cbfbbe74933ee636d603a82d12_/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/home/lbergstrand/rnd/hybrid_assembly_pipeline/scratch_space/conda_envs/e64245cbfbbe74933ee636d603a82d12_/lib/python3.8/site-packages/gtdbtk/main.py", line 816, in parse_options
    self.identify(options)
  File "/home/lbergstrand/rnd/hybrid_assembly_pipeline/scratch_space/conda_envs/e64245cbfbbe74933ee636d603a82d12_/lib/python3.8/site-packages/gtdbtk/main.py", line 271, in identify
    markers.identify(genomes,
  File "/home/lbergstrand/rnd/hybrid_assembly_pipeline/scratch_space/conda_envs/e64245cbfbbe74933ee636d603a82d12_/lib/python3.8/site-packages/gtdbtk/markers.py", line 203, in identify
    genome_dictionary = prodigal.run(genomes, tln_tables)
  File "/home/lbergstrand/rnd/hybrid_assembly_pipeline/scratch_space/conda_envs/e64245cbfbbe74933ee636d603a82d12_/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 220, in run
    raise ProdigalException(f'An exception was caught while running Prodigal: {e}')
gtdbtk.exceptions.ProdigalException: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.
================================================================================
```

Unknown, I activated the gtdbtk environment built by conda and ran prodigal manually and no error code occurred. I also tried to update the version of gtdbtk.

### Problem Solution

gtdbtk classify_wf -h has a ```--genes   indicates input files contain called genes (skip gene calling). Warning: This flag will also skip the ANI comparison steps (ani_screen and classification). (default: False)``` flag.

@jmtsuji Have you encountered this error before?

**Comment by LeeBergstrand** [comment]
I upgraded to the latest version of GTDBtk, but I had to add the ```--skip_ani_screen``` flag to ```classify_wf``` to get it to work. They want you to build a MASH db beforehand.

**Comment by jmtsuji** [comment]
Hmm, odd issue with prodigal -- I've never seen this before. Could be an install issue. I think it's reasonable to go ahead and update GTDB-Tk to the most recent version and to update the GTDB database to r214.1 (as discussed in #32 ).

With this new version, it sounds like we will need to add a step to the GTDB setup rule (or make a separate rule) to set up a MASH db.

**Comment by LeeBergstrand** [comment]
Sounds good. I will add the ```--skip_ani_screen``` flag to my branch until this is resolved.

**Comment by LeeBergstrand** [comment]
I just saw this in the FAQ:

```
Using the --mash_db option will indicate to GTDB-Tk the path of the sketched Mash database require for ANI screening.
If no database are available ( i.e. this is the first time running classify ), the --mash_db option will sketch a new Mash database that can be used for subsequent calls.
```
So if we give it the correct path to the ```mash_db``` and there is not one it will make one.

**Comment by LeeBergstrand** [comment]
I think that this step can be used to rebuild the database.

 https://ecogenomics.github.io/GTDBTk/commands/ani_rep.html

**Comment by LeeBergstrand** [comment]
> @LeeBergstrand thanks for finding this. It would be great if `gtdbtk ani_rep` could be run independently from the main workflow. If so: as part of a GTDB setup rule, maybe we could run `gtdbtk ani_rep` on the [test dataset included with the GTDB](https://github.com/Ecogenomics/GTDBTk/tree/master/tests/data/genomes_gz) (used in `gtdb test`) with the `--mash_db` flag, just to build the mash database?

So I added the ```--mash_db``` to the ```run_gtdb``` rule as a temporary fix in  https://github.com/jmtsuji/rotary/commit/081a99f6149275938239879b8a7daaaa1f332fe1 it looks to me that I think this fix will skip making a mash db if one was already created. Running it now to see what output files this generates. 

We need to make a separate rule for this as ```ani_rep``` requires the assembled genomes. Or we generate the reference sketch directly using ```mash```.  The output files for ```ani_rep``` are the following:

```
[prefix].ani_closest.tsv
[prefix].ani_summary.tsv
[prefix].log
[prefix].warnings.log
[prefix].warnings.log
intermediate_results/mash/
    [prefix].gtdb_ref_sketch.msh
    [prefix].mash_distances.msh
    [prefix].user_query_sketch.msh
```

So, I think we need to generate the ```gtdb_ref_sketch.msh``` file. I'll check their code to see how they do it.

**Comment by jmtsuji** [comment]
Thanks for making the temporary fix and for looking into this issue more deeply!

> So I added the --mash_db to the run_gtdb rule as a temporary fix in https://github.com/jmtsuji/rotary/commit/081a99f6149275938239879b8a7daaaa1f332fe1 it looks to me that I think this fix will skip making a mash db if one was already created. Running it now to see what output files this generates.

I agree with you, I think it will make a Mash DB if one does not already exist, and it will skip making a Mash DB if one does exist. Curious what the output of your test run will look like.

One comment: my impression (just from reading the docs) was that `--mash_db` creates a sketch of the GTDB's DB itself (not the user's input genomes), so the Mash DB only needs to be generated once. Otherwise, it seems odd to me that the GTDB-Tk tool devs would even include a flag to output the Mash DB, rather than keeping the Mash DB as a temp file. But it's odd that there is seemingly no way to run the Mash DB generation step without giving user-supplied genomes, in that case. Anyway, will be interesting to dive into the GTDB-Tk code more deeply and also do a test run of GTDB-Tk -- thanks for doing this. If it turns out that the generated Mash DB is actually generic (rather than run-specific), then the Mash DB could be saved into rotary's DB folder rather than the run output folder. Anyway, thanks again!

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/jmtsuji/rotary/commit/219c5a58e2a6daedf11c544f5ae514ae1fcea324, where we build the reference mash db and store it in the database folder.

I looked through their code and learned how they ran mash within the ```classify wf``` command. It turns out they were running the following command:

```
mash sketch -l -p 4 /tmp/gtdbtk_mash_tmp_qm841e_g/genomes.txt -o annotation/gtdbtk/run_files/BS6_sketch.msh -k 16 -s 5000      
```

Where ```genomes.txt```contains a list of the paths to all the genomes in the GTDBtk database.


The command ```--mash_db``` has documentation that it is the mash DB for all the references.

```
path to save/read (if exists) the Mash reference sketch database (.msh)`
```

So, that means this flag only leads to the reference database (GTDB), not the query.
