### ISSUE TITLE
GTDB download version is hard coded.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#32]
### Problem Description

In ```rotary.smk```, the subversion of GTDB to download is hardcoded a ```_V2```. This causes downloads to fail if there is not yet a ```_V2``` version.

```
params:
        db_dir_root=os.path.join(config.get("db_dir")),
        initial_download_dir=os.path.join(config.get("db_dir"), "release" + VERSION_GTDB + "_v2"),
        db_dir=os.path.join(config.get("db_dir"), "GTDB_" + VERSION_GTDB),
        url="https://data.gtdb.ecogenomic.org/releases/release" + VERSION_GTDB + "/" + VERSION_GTDB + ".0/auxillary_files/gtdbtk_r" + VERSION_GTDB + "_v2_data.tar.gz"
    shell:
```

### Problem Solution

The ```_V``` of version number should be included in ```VERSION_GTDB```

i.e., replace 

```
VERSION_GTDB="214" 
```

with

```
VERSION_GTDB="214_V1" 
```

**Comment by jmtsuji** [comment]
Unfortunately, this is an issue with an inconsistency in the GTDB download URL syntax. "V2" was added to r207 to fix an unexpected bug with r207's initial release, I think. This "V__" URL format is not followed in other releases, including r214. This is why I hard-coded "V2" into the `download_gtdb_db` and left a TODO comment there describing the problem.

For r214, it appears that a more consistent URL format is being followed. There are now [`r214.0` and `r214.1` releases](https://data.gtdb.ecogenomic.org/releases/release214/). I think we could use this syntax (`r[RELEASE].[SUBVERSION]`) to build a more robust downloader.

**Comment by LeeBergstrand** [comment]
Sounds good, I think using the Syntax above makes sense. You can also go to the URL https://data.gtdb.ecogenomic.org/releases/latest/ to get the latest version. However, I assume you would want the ability to version lock for reproducibility.

**Comment by jmtsuji** [comment]
Agreed, being able to version lock for reproducibility is best. My hope is that the GTDB will continue to make their URL syntax more stable/predictable over time as they get used to releasing minor version updates etc., making it easier to update software pipelines between GTDB releases in future.

Let's proceed with using the above mentioned syntax to determine the download URL.

**Comment by LeeBergstrand** [comment]
@jmtsuji Addressed in https://github.com/jmtsuji/rotary/commit/7ab379168e5302452ae59ea26cd524e450506157

**Comment by jmtsuji** [comment]
Great, thanks!
