### ISSUE TITLE
Add CheckM for genome completeness calculation

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#36]
I propose adding CheckM for genome completeness calculations.

**Comment by LeeBergstrand** [comment]
CheckM2 https://www.nature.com/articles/s41592-023-01940-w

**Comment by jmtsuji** [comment]
Agreed -- I'm OK with using CheckM2 to calculate completeness/contamination.

**Comment by LeeBergstrand** [comment]
Completed by https://github.com/jmtsuji/rotary/pull/76
