### ISSUE TITLE
Add genome coverage and depth calculations for both nanopore and illumina.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#37]
I'm not sure if this information has been calculated yet. We would simply take the finalized genome and map the Illumina reads using BBmap and then the nanopore reads using minimap2. We would then take the resulting SAM/BAM files and run `samtools coverage` and add them to some sort of report.

**Comment by jmtsuji** [comment]
@LeeBergstrand This is already implemented in [rule calculate_final_long_read_coverage](https://github.com/jmtsuji/rotary/blob/865c59e40242092f8e3ca97f31fd8b26bcef5513/rules/rotary.smk#L1111) and [rule calculate_final_short_read_coverage](https://github.com/jmtsuji/rotary/blob/865c59e40242092f8e3ca97f31fd8b26bcef5513/rules/rotary.smk#L1079C5-L1079C45). The `samtools coverage` outputs are saved in `annotation/coverage` in the output folder. Hope this helps!
