### ISSUE TITLE
Create CLI

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#39]
Complete CLI commands:

- [x] `rotary run` - runs or rerun a rotary run on one or more samples in an initialized rotary project directory
- [x] `rotary run_one` - run the rotary workflow on a single sample (sequence files are specified in the command)
- [x] `rotary init` - initialize a rotary project directory for multiple samples (sequence files are stored in a directory)

**Comment by LeeBergstrand** [comment]
@jmtsuji Do you think we should add a `rotary download` command eventually?

**Comment by jmtsuji** [comment]
Yeah, that would make sense to add a `rotary download` command eventually. I think this should be pretty straightforward:
- All commands that involve DB downloads are summarized at the top of the snakefile at the moment.
- An additional checkpoint-like rule (e.g., `rule download`) could be added to summarize the outputs from these rules. 
- Then, it would be easy to call this `download` rule via snakemake using the `--until` flag, with very similar code as would be used in `rotary run`.

**Comment by jmtsuji** [comment]
Note: I'm not sure if there is any way to pre-install all the conda environments needed by rotary. Snakemake handles this internally and installs them on an as-needs basis by default.

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/jmtsuji/rotary/commit/b89fb0cd658d4f445d2c9969a7cb467f04680d6f
