### ISSUE TITLE
Create auto install of all code and CLI

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#41]
Completed using setuptools and pip. One can now run `pip install --editable .` and rotary will be installed. One needs to create a conda environment with `environment.yaml` before running `pip`.

**Comment by jmtsuji** [comment]
Great that this is working in basic form!

**Comment by LeeBergstrand** [comment]
Complete as of https://github.com/jmtsuji/rotary/commit/b89fb0cd658d4f445d2c9969a7cb467f04680d6f
