### ISSUE TITLE
Modify the workflow to add multi-sample capability

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#43]
### Problem Description
Currently, the sample names are provided in the config file. This means Rotary can only run on one sample at a time. Instead, we would like the capability to run multiple samples at once.

### Problem Solution

The new CLI, built on the `develop_lee` branch, creates a `samples. tsv` file that lists one or more samples and their assigned input file paths. We should use this file as input for Rotary and modify the workflow so it processes multiple samples, where each sample result is stored in its folder.

**Comment by jmtsuji** [comment]
This change will be somewhat involved -- we'll have to add a new wildcard for samples (which are static right now) and carry the new wildcard through the whole workflow. I'm also not sure how to connect the `samples.tsv` file to snakemake -- the ATLAS CLI could be a good reference for this.

**Comment by LeeBergstrand** [comment]
The easiest way would be to provide a path to the sample table in the config file and then parse it in the snakemake file. You can then define a Python function in the snakemake file to parse the TSV. We might also be able to use my sample class defined in `sample.py`.

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/jmtsuji/rotary/pull/71
