### ISSUE TITLE
Modify python scripts so they can be called directly rather than downloaded.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#47]
### Problem Description

The Python scripts for end repair are installed by downloading them from GitHub. 

```
rule install_internal_scripts:
    output:
        end_repair=os.path.join(config.get("db_dir"), "rotary-" + VERSION, "scripts", "flye_end_repair.sh"),
        end_repair_utils=os.path.join(config.get("db_dir"), "rotary-" + VERSION, "scripts", "flye_end_repair_utils.py"),
        install_finished=os.path.join(config.get("db_dir"), "checkpoints", "internal_scripts_" + VERSION)
    log:
        "logs/download/install_internal_scripts.log"
    benchmark:
        "benchmarks/download/install_internal_scripts.txt"
    params:
        db_dir=config.get("db_dir"),
        url="https://github.com/jmtsuji/rotary/archive/refs/tags/" + VERSION + ".tar.gz"
    shell:
        """
        mkdir -p {params.db_dir}
        wget -O - {params.url} 2> {log} | tar -C {params.db_dir} -xzf - >> {log} 2>&1
        touch {output.install_finished}
        """
```

Because the scripts are already included in the repo, they should be installed during installation rather than downloaded from Github. 

### Problem Solution

Because all the scripts are being converted to Python, we can install them alongside `rotary.py` using our `pyproject.toml` file. However, it should be noted that the argsparse code must be placed in its function as I did in `rotary.py`. When installing via `pyproject.toml`, the resulting CLI scripts call functions in the Python files directly rather than the overall Python file.

```
[project.scripts]
rotary = "rotary.rotary:main"
```

See: https://github.com/jmtsuji/rotary/blob/99209d8158a6df68949fecd21180787562ab35b2/rotary/rotary.py#L34

**Comment by LeeBergstrand** [comment]
@jmtsuji This was weird and confusing for me. So basically, when pip installs via `pyproject.toml`, it creates a script that calls the `main()` function in your Python code. Because of this, other overall Python script is not called, so you must include the args parsing code as a dedicated function called by `main().`

For an example, See: https://github.com/jmtsuji/rotary/blob/develop_lee/rotary/rotary.py

**Comment by jmtsuji** [comment]
Yes, agreed, we should properly install `repair.py` rather than downloading it from Github. Thanks for the advice... I'll try to format the script like you mentioned, with a dedicated parser function called by main().

**Comment by jmtsuji** [comment]
@LeeBergstrand Quick question about file organization:
Considering that we will probably only have Python code in the `scripts` folder now, would it be better to rename this folder something like `modules`? Or remove this folder entirely and move the Python code files directly into the main `rotary` folder, like is the case for `utils.py` etc.? As discussed in #23, my long-term hope is that the code in what is now the `scripts` folder will be directly runnable as modules via the rotary CLI. (I'm not that familiar with Python package management and the best way to arrange the files for that to happen.) Thanks!

**Comment by LeeBergstrand** [comment]
> @LeeBergstrand Quick question about file organization:
> Considering that we will probably only have Python code in the `scripts` folder now, would it be better to rename this folder something like `modules`? Or remove this folder entirely and move the Python code files directly into the main `rotary` folder, like is the case for `utils.py` etc.? As discussed in #23, my long-term hope is that the code in what is now the `scripts` folder will be directly runnable as modules via the rotary CLI. (I'm not that familiar with Python package management and the best way to arrange the files for that to happen.) Thanks!

@jmtsuji I would move the Python code files directly into the main rotary folder for now.

**Comment by jmtsuji** [comment]
@LeeBergstrand The repair.py module is now working (pending some further edge case handling and refactoring) in the [end_repair](https://github.com/jmtsuji/rotary/tree/end_repair) branch. I'd like to add it to rotary's CLI so that it can be called through rotary in the snakemake rules. This allows me to call the repair module like this in the snakefile in rule assembly_end_repair:

[Lines 352-355](https://github.com/jmtsuji/rotary/blob/24f032885acc133f59422b87e17ff70ec1e69e65/rotary/rules/rotary.smk#L352)
```
rotary repair -l {input.qc_long_reads} -a {input.assembly} -i {input.info} -o {params.output_dir} \
          -f {params.flye_input_mode} -F {params.flye_read_error} -I {params.min_id} \
          -L {params.min_length} -e {params.ref_end} -E {params.reassemble_end} -t {threads} -m {resources.mem} \
          > {log} 2>&1
```
(Until the repair module is callable through the CLI, it's difficult to actually test if the overall workflow is actually working)

What do you think would be a suitable way to add repair.py to the CLI? This might need to be moved to a separate issue. Thanks so much.

**Comment by LeeBergstrand** [comment]
@jmtsuji Adding it as a sub-command might be tricky as it would require calling `repair.py` from `rotary.py.` To support this change, I would likely refactor rotary.py so that the `if else` block for the subcommands is at the top and the args parsing is in a function for each command. Seems like a lot of work. We would have to do this refactoring to support https://github.com/jmtsuji/rotary/issues/23.

To get things working, we can add rotary repair directly as a script. For example, we can name it `rotary-repair`.

https://github.com/jmtsuji/rotary/blob/24f032885acc133f59422b87e17ff70ec1e69e65/pyproject.toml#L30

In the `pyproject.toml` you can add a new line to the scripts parameter.

```toml
rotary-repair = "rotary.repair:main"
```

Then, you can run `pip install --editable .` into the project directory, which should add a rotary-repair command to the current environment.

**Comment by LeeBergstrand** [comment]
This is a workaround until the sub-commands can be appropriately implemented.

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/jmtsuji/rotary/commit/1207cc02caa0c277acf33373a87ce2846546094a

**Comment by LeeBergstrand** [comment]
> ```toml
> rotary-repair = "rotary.repair:main"
> ```

```name-of-script-in-cli = "package_name.script_name:function_to_call_in_script"```

Thats how the above works. So `main()` is an CLI `enterypoint`.

If you look at the code inside `rotary-repair` it looks like this:

```python
#!/Users/lee/miniforge3/envs/rotary/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from rotary.repair import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

**Comment by jmtsuji** [comment]
Great, this is also working on my end now -- let's use this as a temporary workaround. I think it's reasonable to close this issue now.
