### ISSUE TITLE
Reverse fix to temporary work around in finalize assembly rule.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#52]
Note this is a temporary workaround and should be changed back to `end_repair` once the end repair module is working. Maybe we should make a TODO so we don't forget?

_Originally posted by @jmtsuji in https://github.com/jmtsuji/rotary/pull/46#discussion_r1363347469_

**Comment by LeeBergstrand** [comment]
@jmtsuji I think this can be repaired in the end repair branch as you work on it.

**Comment by jmtsuji** [comment]
OK, sounds good.

**Comment by jmtsuji** [comment]
Addressed in [97a766b](https://github.com/jmtsuji/rotary/commit/97a766b53f026c3292c5d0b000355b70daff8400) and [0b32b6b](https://github.com/jmtsuji/rotary/commit/0b32b6bdd5e27ba97cf10b516511a0c6b2a2b939)
