### ISSUE TITLE
File naming error in sample.py

### ISSUE THREAD

**Issue by jmtsuji** [jmtsuji/rotary#61]
## Environment
Rotary end_repair commit [9a4678b](https://github.com/jmtsuji/rotary/commit/9a4678b9a03865c2f295079feedc368139fce0a2)
Running on a Linux (Ubuntu) server

## Problem description
With the following files in my `input` folder:
```
S18_long.fastq.gz  S18_R1.fastq.gz  S18_R2.fastq.gz
```

When I run `rotary init -o output_dir -d rotary_db_dir -i input`, I get the following error:
```
Traceback (most recent call last):
  File "/Analysis/jmtsuji/miniconda3_me23/envs/rotary_tmp/bin/rotary", line 8, in <module>
    sys.exit(main())
  File "/Analysis/jmtsuji/projects/tool_development/2022_08_01_rotary_testing/rotary/rotary/rotary.py", line 122, in main
    init(args, config, output_dir_path)
  File "/Analysis/jmtsuji/projects/tool_development/2022_08_01_rotary_testing/rotary/rotary/rotary.py", line 202, in init
    file = SequencingFile(file_path=(os.path.join(input_path, file)))
  File "/Analysis/jmtsuji/projects/tool_development/2022_08_01_rotary_testing/rotary/rotary/sample.py", line 26, in __init__
    raise ValueError(f'{self.name} is not a fastq file.')
ValueError: S18_R2.fastq.gz is not a fastq file.
```

## Possible cause
I think this is because the `.gz` is not being handled properly by `os.path.splitext()` in [sample.py, class SequencingFile](https://github.com/jmtsuji/rotary/blob/9a4678b9a03865c2f295079feedc368139fce0a2/rotary/sample.py#L23)
```python
    def __init__(self, file_path):
        self.path = file_path
        self.name = os.path.basename(self.path)

        file_extension = os.path.splitext(self.name)[1]

        if 'fastq' not in file_extension and 'fq' not in file_extension:
            raise ValueError(f'{self.name} is not a fastq file.')

        ...
```
Perhaps just the `.gz` is being saved as not the `.fastq`?

## Proposed solution
Maybe the easiest workaround would be to add a test for if the file has a `.gz` extension and then handle it differently.

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/jmtsuji/rotary/pull/64

**Comment by jmtsuji** [comment]
Thanks -- your proposed change looks good to me.
