### ISSUE TITLE
GTDB-Tk installation error

### ISSUE THREAD

**Issue by jmtsuji** [jmtsuji/rotary#87]
## Problem description
The first time rotary is run on a system, GTDB-Tk works fine. However, when rotary is re-run, if a re-install of the GTDB-Tk conda env is needed (e.g., due to a change in the [env YAML file](https://github.com/jmtsuji/rotary/blob/06e2be93bc63dca17cce12b0ac5834fd26a1e69f/rotary/envs/gtdbtk.yaml)), GTDB-Tk will fail to run due to the GTDB root dir not being set.

Version: Working with the current develop branch (around commit [06e2be9](https://github.com/jmtsuji/rotary/commit/06e2be93bc63dca17cce12b0ac5834fd26a1e69f))
System: Linux (Ubuntu 22.04)

## Possible cause
Rule [setup_gdtb](https://github.com/jmtsuji/rotary/blob/06e2be93bc63dca17cce12b0ac5834fd26a1e69f/rotary/rules/rotary.smk#L229C1-L229C17) sets the GTDB root dir (`GTDBTK_DATA_PATH`) in the GTDB-Tk conda env. After this rule is run, it saves a checkpoint file in the rotary DB dir (in `checkpoints/GTDB_[VERSION_GTDB_COMPLETE]_setup`). Because the setup file is saved in the rotary DB dir and not in the individual run dir, it means that the setup rule will never be run again if that DB dir is used, even if a new GTDB-Tk conda env is installed. Thus, new GTDB-Tk conda envs will not have the GTDB root dir set.

## Possible solutions
This problem should be pretty easy to address. Here are two possible solutions:
- Make rule setup_gtdb save the checkpoint file in the rotary run (output) dir. This way, the rule will be re-run each time that rotary is run.
- Delete the setup_gtdb rule and instead set `GTDBTK_DATA_PATH` in [rule run_gtdbtk](https://github.com/jmtsuji/rotary/blob/06e2be93bc63dca17cce12b0ac5834fd26a1e69f/rotary/rules/rotary.smk#L1397). This way, the GTDB DB path will be set just before GTDB-Tk is run.

The only case where I could see one of these working better than the other is if a different program was trying to use the same GTDB-Tk conda env with a different GTDB dir. In that case, it would be better to set `GTDBTK_DATA_PATH` just before GTDB-Tk is run (solution 2 above) to avoid accidentally using the wrong GTDB. However, I imagine this kind of conflict would be very rare. It would be ideal if `GTDBTK_DATA_PATH` could be set as a flag of GTDB-Tk, but I don't see an option to do this.

@LeeBergstrand What's your favoured approach? Thanks!

**Comment by jmtsuji** [comment]
@LeeBergstrand I just made a PR (#88) for proposed fix 2 in the issue above. After thinking about it, I think this fix is better than fix 1, because:

- It prevents accidental collisions if another program happens to be using the same GTDB-TK conda env with a different GTDB release
- The GTDB data path is not permanently set in the conda env. Thus, each time that conda env is used, the user needs to specify the GTDB data path, or else GTDB-Tk will throw an informative error. This further helps avoid accidental collisions (e.g., if someone wants to use this GTDB-Tk with a different GTDB release but doesn't realize the DB is fixed as a global variable).

Thoughts? Feel free to review my PR or to close it if you think a different solution would be better. Thanks!

**Comment by LeeBergstrand** [comment]
@jmtsuji I agree with your assessment. It simplify's the code.
